# Generated by Django 2.0.1 on 2018-02-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistpainting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
